---
title: "Lung Cancer Prediction using KNN Algorithm-Team Quatum"

output: html_document
---
## Install language server
```{r setup, include=FALSE}
if (require("languageserver")) {
  require("languageserver")
} else {
  install.packages("languageserver", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}


if (require("languageserver")) {
  require("languageserver")
} else {
  install.packages("languageserver", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

# Introduction ----
#The algorithm that is used is the KNN algorithm with caret

# STEP 1. Install and Load the Required Packages below ----
library(readr)
## stats ----
if (require("stats")) {
  require("stats")
} else {
  install.packages("stats", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## mlbench ----
if (require("mlbench")) {
  require("mlbench")
} else {
  install.packages("mlbench", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## caret ----
if (require("caret")) {
  require("caret")
} else {
  install.packages("caret", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## MASS ----
if (require("MASS")) {
  require("MASS")
} else {
  install.packages("MASS", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## glmnet ----
if (require("glmnet")) {
  require("glmnet")
} else {
  install.packages("glmnet", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## e1071 ----
if (require("e1071")) {
  require("e1071")
} else {
  install.packages("e1071", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## kernlab ----
if (require("kernlab")) {
  require("kernlab")
} else {
  install.packages("kernlab", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## rpart ----
if (require("rpart")) {
  require("rpart")
} else {
  install.packages("rpart", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}







lung_cancer <- read_csv("data/survey lung cancer.csv",
           col_types =
             cols(
               GENDER = col_character(),
               AGE = col_integer(),
               SMOKING = col_integer(),
               YELLOW_FINGERS= col_integer(),
               PEER_PRESSURE = col_integer(),
               CHRONIC_DISEASE = col_integer(),
               FATIGUE = col_integer(),
               ALLERGY = col_integer(),
               WHEEZING = col_integer(),
               ALCOHOL_CONSUMING = col_integer(),
               SHORTNESS_OF_BREATH = col_integer(),
               SWALLOWING_DIFFICULTY = col_integer(),
               CHEST_PAIN = col_integer(),
            
               LUNG_CANCER =
                 col_factor(levels =
                              c("YES",
                                "NO")),
               
               
               # license = col_skip()
             ))
### 3.d. kNN for a regression problem with CARET's train function ----
#### tHE DATASET IS Loaded and it is split ----
data(lung_cancer)

# Define an 80:20 train:test data split of the dataset.
train_index <- createDataPartition(lung_cancer$LUNG_CANCER,
                                   p = 0.8,
                                   list = FALSE)
lung_cancer_train <- lung_cancer[train_index, ]
lung_cancer_test <- lung_cancer[-train_index, ]

####In this step the model is  trained ----
# We apply the 5-fold cross validation resampling method
# We also apply the standardize data transform
set.seed(7)
train_control <- trainControl(method = "cv", number = 5)
lung_caret_model_knn <- train(LUNG_CANCER ~ ., data = lung_cancer,
                                 method = "knn", metric = "Accuracy",
                                 preProcess = c("center", "scale"),
                                 trControl = train_control)

#### Display the model's details ----
print(lung_caret_model_knn)

#### Predictions are then made ----
predictions <- predict(lung_caret_model_knn,
                       lung_cancer_test[, 1:16])


#### The model's evaluation metrics is then displayed ----

confusion_matrix <-
  caret::confusionMatrix(predictions,
                         lung_cancer_test[, 1:16]$LUNG_CANCER)
print(confusion_matrix)

fourfoldplot(as.table(confusion_matrix), color = c("grey", "lightblue"),
             main = "Confusion Matrix")

